language: csharp
solution: ScaphandreEngine.sln
os: windows
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
- nuget restore ScaphandreEngine.sln
script:
- msbuild /p:Configuration=Release ScaphandreEngine.sln
- "./scripts/copyScaphandreToInstaller.bat"
after_script:
- cd ./ScaphandreInstaller/bin/Release
- 7z a -tzip ../../../scaphandre-installer.zip *.dll *.exe Scaphandre/*.dll -ssc
- cd ../../..
deploy:
  provider: releases
  api_key:
    secure: b1p4ZYcHJ+mhwk+Uoe/S7MLPqBvyS/dqK1E7X8DtyFOp6SD9DE6R3JADQbmBD6rmdfdrZ8yp0esxApEvTbUcLzOMFSYdKvKbTahBLQqnHS0C9A8X+Kc6W6Ab+EVjlbA0ZhLQVSG7LxDLuW6779SfQvc9X5jEMZh9hpP/pTIIl9b4PCSbo9rCnvduDFiAkS0ZSezo7QSgJ3wGXdc6IddAsoyNvNhcfP2jkoxVHCH0RVbpGjKoRyXzMFF5AOduf+9/Ge51FNDNhNHKxME7K3+Jwq//1x+m9ARj+S31TUEQbceWiGfUgrH7mDKKcWKkr3Bndq8XJJsrJPuVM+xVXphoxP7YQLLytHJcBSpBlwI1aLDycbQwaTMeXlJpyGHkd6yvsL97YN9rzDkzxE0MoTp+YRICCG/inQ1w8MVzDbb/AELlzruusQo8vgyCXyJl9UQzHwH5ClzVDGKgDwU+albxSxfajnHpdqjpjWMGwtuHSVo4TQ2X4gcH/Kvtf9050xEdC74BgtDtncMpq8AhlDsaH3GdqduYKbLdR1u2uRfEUWMRWfKZL9Yei3+BBm/srIQCssomFzXn1lFFrlQXpDOC7KmTAdCtw4VT5B+re5exnHX0Yyx93avaICWLLM9EAe6oOr29XV6nm2dfVcFtPgxJjD0QGT3vFlHNfI6KkPFJvQU=
  file: scaphandre-installer.zip
  on:
    repo: Norech/scaphandre-engine
