language: csharp
solution: ScaphandreEngine.sln
mono: latest
install:
- nuget restore ScaphandreEngine.sln
- rm -r _Dependencies
- git clone $TRAVIS_DEPENDENCIES_REPO _Dependencies
- chmod +x ./scripts/copyScaphandreToInstaller
script:
- msbuild /p:Configuration=Release /p:AllowedReferenceRelatedFileExtensions=none ScaphandreEngine.sln
- "./scripts/copyScaphandreToInstaller Release $PWD"
- cd ./ScaphandreInstaller/bin/Release
- 7z a -tzip ../../../scaphandre-installer.zip *.dll *.exe Scaphandre/*.dll -ssc
- cd ../../..
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: scaphandre-installer.zip
  skip_cleanup: true
  on:
    tags: true
